# encryptionKey is used for envcrypting sensitive data in the DB
# make sure you change it and keep persistent otherwise the app won't be able to decrypt the data
encryptionKey: eek3eagheCo1phah4shi2Nai3ce8tiehaeVe5baph6Aixi9oorai5iepa1woh4ieQuaiz4outhakeixohn6aech8riep7beeluum

# logLevel valid options are as follows, from most to least verbose:
# trace
# debug
# info
# warn
# error
# fatal
# panic
logLevel: debug

# MikroTik API pollers, defaults to `1` if ommited
# it is recommended to have at lest 2 pollers in order to mitigate possible network issues,
# i.e. if a devices times out this will slow down polling for other resources as they will be waiting in the queue
apiPollers: 2

# devicePollerInterval defines how often devices should be polled,
# the time is between finish of a previous run and start of the new one
# defaults to 300 seconds if ommited
# valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
# devicePollerInterval: 30s

# full or relative path to the database, defaults to `database.clover` if ommited
# the path will be created and new DB initialised if missing
dbPath: database.clover

# full or relative path to the backups
# the path will be created
backupPath: backups

# MikroManager export workers, can be ommited or set to 0 if backups are not created
exportWorkers: 10
